#include <unordered_map>
#include <SFML/Window/Keyboard.hpp>

std::unordered_map<int, sf::Keyboard::Key> INPUT_KEY_TABLE = {

    // ===== CONTROLE =====
    {27,  sf::Keyboard::Escape},
    {13,  sf::Keyboard::Enter},
    {9,   sf::Keyboard::Tab},
    {8,   sf::Keyboard::Backspace},
    {32,  sf::Keyboard::Space},
    {19,  sf::Keyboard::Pause},
    {45,  sf::Keyboard::Insert},
    {46,  sf::Keyboard::Delete},
    {36,  sf::Keyboard::Home},
    {35,  sf::Keyboard::End},
    {33,  sf::Keyboard::PageUp},
    {34,  sf::Keyboard::PageDown},

    // ===== SETAS =====
    {37,  sf::Keyboard::Left},
    {38,  sf::Keyboard::Up},
    {39,  sf::Keyboard::Right},
    {40,  sf::Keyboard::Down},

    // ===== MODIFICADORES =====
    {16,  sf::Keyboard::LShift},
    {17,  sf::Keyboard::LControl},
    {18,  sf::Keyboard::LAlt},
    {91,  sf::Keyboard::LSystem},
    {92,  sf::Keyboard::RSystem},
    {93,  sf::Keyboard::Menu},

    // ===== NÚMEROS (TOP ROW) =====
    {48,  sf::Keyboard::Num0},
    {49,  sf::Keyboard::Num1},
    {50,  sf::Keyboard::Num2},
    {51,  sf::Keyboard::Num3},
    {52,  sf::Keyboard::Num4},
    {53,  sf::Keyboard::Num5},
    {54,  sf::Keyboard::Num6},
    {55,  sf::Keyboard::Num7},
    {56,  sf::Keyboard::Num8},
    {57,  sf::Keyboard::Num9},

    // ===== LETRAS =====
    {65,  sf::Keyboard::A},
    {66,  sf::Keyboard::B},
    {67,  sf::Keyboard::C},
    {68,  sf::Keyboard::D},
    {69,  sf::Keyboard::E},
    {70,  sf::Keyboard::F},
    {71,  sf::Keyboard::G},
    {72,  sf::Keyboard::H},
    {73,  sf::Keyboard::I},
    {74,  sf::Keyboard::J},
    {75,  sf::Keyboard::K},
    {76,  sf::Keyboard::L},
    {77,  sf::Keyboard::M},
    {78,  sf::Keyboard::N},
    {79,  sf::Keyboard::O},
    {80,  sf::Keyboard::P},
    {81,  sf::Keyboard::Q},
    {82,  sf::Keyboard::R},
    {83,  sf::Keyboard::S},
    {84,  sf::Keyboard::T},
    {85,  sf::Keyboard::U},
    {86,  sf::Keyboard::V},
    {87,  sf::Keyboard::W},
    {88,  sf::Keyboard::X},
    {89,  sf::Keyboard::Y},
    {90,  sf::Keyboard::Z},

    // ===== FUNÇÕES =====
    {112, sf::Keyboard::F1},
    {113, sf::Keyboard::F2},
    {114, sf::Keyboard::F3},
    {115, sf::Keyboard::F4},
    {116, sf::Keyboard::F5},
    {117, sf::Keyboard::F6},
    {118, sf::Keyboard::F7},
    {119, sf::Keyboard::F8},
    {120, sf::Keyboard::F9},
    {121, sf::Keyboard::F10},
    {122, sf::Keyboard::F11},
    {123, sf::Keyboard::F12},

    // ===== NUMPAD =====
    {96,  sf::Keyboard::Numpad0},
    {97,  sf::Keyboard::Numpad1},
    {98,  sf::Keyboard::Numpad2},
    {99,  sf::Keyboard::Numpad3},
    {100, sf::Keyboard::Numpad4},
    {101, sf::Keyboard::Numpad5},
    {102, sf::Keyboard::Numpad6},
    {103, sf::Keyboard::Numpad7},
    {104, sf::Keyboard::Numpad8},
    {105, sf::Keyboard::Numpad9},
    {107, sf::Keyboard::Add},
    {109, sf::Keyboard::Subtract},
    {106, sf::Keyboard::Multiply},
    {111, sf::Keyboard::Divide},
    {110, sf::Keyboard::Decimal},

    // ===== SÍMBOLOS =====
    {186, sf::Keyboard::Semicolon},
    {187, sf::Keyboard::Equal},
    {188, sf::Keyboard::Comma},
    {189, sf::Keyboard::Hyphen},
    {190, sf::Keyboard::Period},
    {191, sf::Keyboard::Slash},
    {192, sf::Keyboard::Tilde},
    {219, sf::Keyboard::LBracket},
    {220, sf::Keyboard::Backslash},
    {221, sf::Keyboard::RBracket},
    {222, sf::Keyboard::Quote},
};
